server:
  port: 8080
  servlet:
    context-path: /

static:
  resources:
    path: /Users/ravooo/Downloads/zhixin/


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zhixin
    username: root
    password: 5523
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: /META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${static.resources.path}

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1